# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
get_predvals <- function(parm_post, X_all, ntotal) {
    .Call(`_NBRegAD_get_predvals`, parm_post, X_all, ntotal)
}

#' @export
get_count <- function(offset, pred_mat, overdisp_post) {
    .Call(`_NBRegAD_get_count`, offset, pred_mat, overdisp_post)
}

rcpp_hello <- function() {
    .Call(`_NBRegAD_rcpp_hello`)
}

